sudo: false
language: python
python:
  - "3.5"
virtualenv:
  system_site_packages: true
install:
  - pip install git+$REPO
script:
  - python -m unittest
notifications:
  webhooks:
    urls:
      - http://rusti.serveo.net/role
  email:
    recipients:
      - j4qfrost@gmail.com
    on_success: always # default: change
