language: python
python:
  - "3.7"
install:
  - pip install git+$REPO
  - python -m factorial
script:
  - python -m unittest
notifications:
  webhooks:
    urls:
      - http://rusti.serveo.net/role
  email:
    recipients:
      - j4qfrost@gmail.com
    on_success: always # default: change
