language: python
python:
  - "3.7"
install:
  - pip install git+$REPO
script:
  - python -m unittest
notifications:
  email:
    recipients:
      - j4qfrost@gmail.com
    on_success: always # default: change
